cities = {
    'москва': 'Moscow',
    'санкт-петербург': 'Saint Petersburg',
    'новосибирск': 'Novosibirsk',
    'екатеринбург': 'Yekaterinburg',
    'казань': 'Kazan',
    'нижний новгород': 'Nizhny Novgorod',
    'челябинск': 'Chelyabinsk',
    'самара': 'Samara',
    'омск': 'Omsk',
    'ростов-на-дону': 'Rostov-on-Don',
    'уфа': 'Ufa',
    'красноярск': 'Krasnoyarsk',
    'воронеж': 'Voronezh',
    'пермь': 'Perm',
    'волгоград': 'Volgograd',
    'краснодар': 'Krasnodar',
    'саратов': 'Saratov',
    'тюмень': 'Tyumen',
    'тольятти': 'Tolyatti',
    'ижевск': 'Izhevsk',
    'барнаул': 'Barnaul',
    'ульяновск': 'Ulyanovsk',
    'иркутск': 'Irkutsk',
    'хабаровск': 'Khabarovsk',
    'махачкала': 'Makhachkala',
    'владивосток': 'Vladivostok',
    'ярославль': 'Yaroslavl',
    'оренбург': 'Orenburg',
    'томск': 'Tomsk',
    'кемерово': 'Kemerovo',
    'новокузнецк': 'Novokuznetsk',
    'рязань': 'Ryazan',
    'набережные челны': 'Naberezhnye Chelny',
    'астрахань': 'Astrakhan',
    'пенза': 'Penza',
    'киров': 'Kirov',
    'липецк': 'Lipetsk',
    'чебоксары': 'Cheboksary',
    'балашиха': 'Balashikha',
    'калининград': 'Kaliningrad',
    'тула': 'Tula',
    'курск': 'Kursk',
    'севастополь': 'Sevastopol',
    'сочи': 'Sochi',
    'ставрополь': 'Stavropol',
    'улан-удэ': 'Ulan-Ude',
    'тверь': 'Tver',
    'магнитогорск': 'Magnitogorsk',
    'иваново': 'Ivanovo',
    'брянск': 'Bryansk',
    'белгород': 'Belgorod'
}